#!/usr/bin/env python2.7

import atexit, socket, sys

port = 80
password = "I am your radiant spark."
secret = sys.argv[1]

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.bind(('', port))
s.listen(5)

atexit.register(lambda: s.close())

while 1:
  c, a = s.accept()
  message = c.recv(4096)
  print "{}:{} {}".format(a[0], a[1], message.strip())
  sys.stdout.flush()
  if message.strip() == password:
    c.send(secret + "\n")
  else:
    c.send("Nope.\n")
  c.close()
