#!/usr/bin/env python2.7

import atexit, socket, sys, thread

port = 49150
password = "I am your radiant spark."
secret = sys.argv[1]

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.bind(('', port))
s.listen(5)

atexit.register(lambda: s.close())

def handle(s, a):
  message = s.recv(4096)
  print "{}:{} {}".format(a[0], a[1], message.strip())
  sys.stdout.flush()
  if message.strip() == password:
    s.send(secret + "\n")
  else:
    s.send("Nope.\n")
  s.close()

while 1:
  try:
    args = s.accept()
    thread.start_new_thread(handle, args)
  except socket.error as e:
    print "Exception: {}".format(e)
